apiVersion: v1
kind: Pod
metadata:
  name: crl-host-pod
  namespace: crl-test
  labels:
    app: crl-host
spec:
  containers:
  - name: httpd
    image: quay.io/centos7/httpd-24-centos7
    ports:
    - containerPort: 8080
      name: http-svc
    volumeMounts:
    #- name: crl-root-cm
      #mountPath: '/var/www/html/root/'
      #readOnly: true
    #- name: crl-intermediate-cm
      #mountPath: '/var/www/html/intermediate/'
      #readOnly: true
  volumes:
  #- name: crl-root-cm
    #configMap:
      #name: crl-root
  #- name: crl-intermediate-cm
    #configMap:
      #name: crl-intermediate
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: crl-host
  namespace: crl-test
spec:
  selector:
    app: crl-host
  ports:
  - protocol: TCP
    port: 80
    targetPort: http-svc
    name: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: crl-host
  namespace: crl-test
  labels:
    app: crl-host
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: crl-host
    weight: 100
  wildcardPolicy: None
