apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: hello
  labels:
    app: hello
spec:
  containers:
  - name: hello
    image: quay.io/centos7/httpd-24-centos7
    ports:
    - containerPort: 8080
      name: hello-http
    volumeMounts:
    - name: http-cm
      mountPath: '/var/www/html/'
      readOnly: true
  volumes:
  - name: http-cm
    configMap:
      name: hello-http
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-http
  namespace: hello
data:
  index.html: |
    Hello CRL Test!
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 80
    targetPort: hello-http
    name: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-service
  namespace: hello
  labels:
    app: crl-test
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: hello-service
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
